name: Benchmark Automation

on:
  workflow_dispatch:
    inputs:
      infinispan_version:
        description: 'Infinispan Version (optional)'
        required: false
        type: string
      jgroups_version:
        description: 'JGroups Version (optional)'
        required: false
        type: string

      # Define the arguments for provisioning the environment.
      aws_region:
        description: 'The AWS region to provision'
        required: false
        default: 'sa-east-1'
        type: string

      aws_cluster_size:
        description: 'The number of nodes to provision'
        required: false
        default: '1'
        type: string

      aws_provision_arguments:
        description: 'Provide custom arguments when provisioning in AWS'
        required: false
        default: ''
        type: string

      # Define the arguments when running the benchmark.
      benchmark_arguments:
        description: 'Provide custom arguments when running the benchmark'
        required: false
        default: ''
        type: string

env:
  ANSIBLE_HOST_KEY_CHECKING: False
  INVENTORY_NAME: 'benchmark-file.yaml'
  CLUSTER_NAME: 'benchmark_runner'

jobs:
  build-application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Build with Maven
        env:
          INFINISPAN_VERSION: ${{ inputs.infinispan_version }}
          JGROUPS_VERSION: ${{ inputs.jgroups_version }}
        run: |
          MVN_CMD="mvn clean install -DskipTests"
          
          if [ -n "$INFINISPAN_VERSION" ]; then
            echo "Overriding Infinispan Version with $INFINISPAN_VERSION"
            MVN_CMD="$MVN_CMD -Dversion.infinispan=$INFINISPAN_VERSION"
          fi
          
          if [ -n "$JGROUPS_VERSION" ]; then
            echo "Overriding JGroups Version with $JGROUPS_VERSION"
            MVN_CMD="$MVN_CMD -Dversion.jgroups=$JGROUPS_VERSION"
          fi

          $MVN_CMD

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-application
          path: target/*
          retention-days: 1

  provision:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create AWS EC2 instances
        id: create-aws-ec2-instances
        uses: ./.github/actions/ec2-create-instances
        with:
          region: ${{ inputs.aws_region }}
          arguments: "-e test_cluster_size=${{ inputs.aws_cluster_size }} ${{ inputs.aws_provision_arguments }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Capture inventory file name
        working-directory: ansible
        run: ls -1 *_inventory.yaml | xargs -L1 -I{} cp {} $INVENTORY_NAME

      - name: Archive infrastructure files
        working-directory: ansible
        run: tar -cf ../infrastructure-state.tar *.pem "$INVENTORY_NAME"

      - name: Encrypt infrastructure
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          .github/scripts/infrastructure-encryption/main.sh \
            encrypt \
            GPG_PASSPHRASE \
            infrastructure-state.tar \
            infrastructure-state.tar.enc

      - name: Upload infrastructure artifacts
        uses: actions/upload-artifact@v4
        with:
          name: infrastructure-state
          path: infrastructure-state.tar.enc
          retention-days: 1

  run-benchmark:
    runs-on: ubuntu-latest
    needs:
      - build-application
      - provision
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download application artifact
        uses: actions/download-artifact@v4
        with:
          name: benchmark-application
          path: target/

      - name: Download infrastructure state
        uses: actions/download-artifact@v4
        with:
          name: infrastructure-state

      - name: Restore infrastructure
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          .github/scripts/infrastructure-encryption/main.sh \
            decrypt \
            GPG_PASSPHRASE \
            infrastructure-state.tar.enc \
            infrastructure-state.tar
          
          tar -xf infrastructure-state.tar -C ansible
          chmod 600 ansible/*.pem

      - name: Install EC2 requirements
        uses: ./.github/actions/ec2-install-requirements
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Include runner in security group
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ inputs.aws_region }}
          SECURITY_GROUP_NAME: ${{ env.CLUSTER_NAME }}
        run: |
          # 1. Get the current public IP of the GitHub runner
          MY_IP=$(curl -s https://checkip.amazonaws.com)
          echo "Allowing Runner IP: $MY_IP in group $SECURITY_GROUP_NAME"

          # 2. Add rule to AWS Security Group (Open Port 22 for this IP only)
          # We use || true to ignore errors if the rule already exists (rare but possible)
          aws ec2 authorize-security-group-ingress \
            --group-name "$SECURITY_GROUP_NAME" \
            --protocol tcp \
            --port 22 \
            --cidr "$MY_IP/32" \
            --region $AWS_REGION || true

      - name: Setup benchmark
        uses: ./.github/actions/benchmark-setup
        with:
          inventory: $INVENTORY_NAME
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Run single benchmark
        uses: ./.github/actions/benchmark-start
        with:
          inventory: $INVENTORY_NAME
          arguments: ${{ inputs.benchmark_arguments }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Show the results
        working-directory: ansible
        run: |
          cat results.csv
          
          echo "Now the txt"
          cat results.txt

  cleanup:
    runs-on: ubuntu-latest
    needs:
      - run-benchmark
      - provision

    if: ${{ always() && needs.provision.result == 'success'  }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download infrastructure state
        uses: actions/download-artifact@v4
        with:
          name: infrastructure-state

      - name: Restore infrastructure
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          .github/scripts/infrastructure-encryption/main.sh \
            decrypt \
            GPG_PASSPHRASE \
            infrastructure-state.tar.enc \
            infrastructure-state.tar

          tar -xf infrastructure-state.tar -C ansible
          chmod 600 ansible/*.pem

      - name: Delete AWS resources
        uses: ./.github/actions/ec2-delete-instances
        with:
          region: ${{ inputs.aws_region }}
          inventory: $INVENTORY_NAME
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
